# Site settings 配置站点
title: '华亚超的个人博客'
description: 'Why so serious?'
keywords: 'Jekyll,华亚超,个人博客,前端,javascript,Windows'
url: 'https://http://onlyhyc.github.io' # your host

# nav 中文字符空格：&emsp;
nav: # 最佳体验 六个标签 且最好每个标签不超过4中文字
  首页: '/'
  # 标签: '/tags.html'
  # 时间线: '/timeline.html'
  关于博主: '/about.html'
  个人简历: '/resume-simple/index.html'


# 博主
author: true
name: '华亚超'
NickName: 'xiaogege'
webtitle: 'hyc'
bio: '致力于成为架构师的前端'
about: true
aboutyou: '&emsp;&emsp;本人毕业于 [ <a href="http://www2017.tyut.edu.cn/">太原理工大学</a> ]，一个毕业于计算机专业，却没有成为程序员的原实施运维工程师，平时爱好学习新的知识，游泳跑步，宅在家学习编程。在博客顶部的个人简历中看到我的项目，这个博客主题也是项目之一，基于ruby+jekyll用 html + css + js 从零写的小项目。当然，要十分感谢一些开源项目，比如 <a href="https://daneden.github.io/animate.css/">css动画库</a> 、<a href="http://www.bootcdn.cn/social-share.js/">
        Bootstrap 中文网开源项目免费 项目 social-share.js</a>  、<a href="http://www.iconfont.cn/">阿里云图标库</a> 、<a href="https://fonts.google.com">谷歌字体库</a> ,以及第三方
        评论系统 [<a href="https://livere.com/">来必力livere</a>]，还有 <a href="https://tongji.baidu.com/web/welcome/login?castk=LTE%3D">百度统计</a> 等等。。。<br>
        &emsp;&emsp;当然还要感谢，jekyll主题开发者 <a href="https://github.com/xukimseven">xukimseven</a>
        是我原先用的博客主题，在使用他与修改他的过程中让我接触与熟悉了 jekyll 这个前端小工具，也促使我写了我自己的主题。'

portraits: '/assets/profile.jpeg' # your portraits image file path

# SNS
SNS: true
SNS-icon: #['Facebook', 'weibo', 'qq', 'github', 'Dribbble', 'Twitter', 'instagram', 'weixin', 'Codepen']
  mail: 'mailto:844875329@qq.com'
  weixin: '/assets/weixin.png'
  qq: '/assets/qq.jpg' # 你的qq二维码存放的地址 or http://wpa.qq.com/msgrd?v=3&uin='你的QQ号'&site=qq&menu=yes
  github: 'https://github.com/onlyhyc'
  # Codepen: ''
  # weibo: ''
  # instagram: ''
  # Twitter: ''
  # Dribbble: ''
  # Facebook: ''
  # Google: ''
  # zhihu: ''
  # juejin: ''
  # twitch: ''

# 分页
paginate: 2
paginatepath: ['page:num']

# since
footer:
  since: 2018

# Markdown
markdown: kramdown
kramdown:
  input: GFM
# 代码高亮 使用rouge
highlighter: rouge
# 代码高亮主题使用pygments主题: autumn\ default\ emacs\ friendly\ manni\ murphy\ pastie\ perldoc\ tango 任选一个你喜欢的主题名称填在下面的单引号中
pygmentsTheme: 'default'

# 友情链接
friends:
  jekyll: 'https://www.jekyll.com.cn/'

# 评论 最佳体验 在disqus、livere和Gitment之间三选一
# disqus 评论
disqus: false
disqus_url: '' # https://abc.disqus.com/embed.js
# 来必力评论
livere: true
livere_uid: 'MTAyMC80MDQ4NC8xNzAxMQ==' # MTAyMC80MDQ4NC8xNzAxMQ==
# Gitment评论 OAuth Application
Gitment: false
Gitment_owner: ''  # github用户名
Gitment_repo: ''  # github博客存放的仓库名
client_id: ''  # 注册 OAuth Application 后获得的 client_id
client_secret: ''  # 注册 OAuth Application 后获得的 client_secret

# Share : weibo, qq, wechat, tencent, douban, qzone, linkedin, diandian, facebook, twitter, google
social-share: true
social-share-items: ['qq', 'wechat', 'weibo']

# 百度统计 在baidu-url里填写自己相关的url代码
baidu: true
baidu-url: ''
# 谷歌分析 在google-ID里填写自己在谷歌分析获得的追踪ID
google: false
google-ID: ''

# 博客头信息备选颜色（该部分在站点中不充当站点变量，将其写在post的头信息中用来充当页面变量）
color: rgb(154,133,255) rgb(255,90,90) rgb(255,210,32) rgb(98,170,255)
